# Generated by Django 3.0.3 on 2021-05-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sequences',
            fields=[
                ('acc_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gene', models.CharField(max_length=20)),
                ('sequence', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='species',
            fields=[
                ('specie_id', models.AutoField(primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=100)),
                ('colloquial_name', models.CharField(max_length=20)),
                ('taxon_id', models.CharField(max_length=25)),
                ('image_specie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='trees',
            fields=[
                ('tree_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
                ('tree_route', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=1000)),
                ('surname', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='used_species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_app.species')),
                ('tree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_app.trees')),
            ],
        ),
        migrations.AddField(
            model_name='trees',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_app.users'),
        ),
        migrations.CreateModel(
            name='specie_sequences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_app.sequences')),
                ('specie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_app.species')),
            ],
        ),
        migrations.CreateModel(
            name='markers',
            fields=[
                ('marker_id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('identification_id', models.IntegerField()),
                ('dataset_key', models.CharField(max_length=150)),
                ('specie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_app.species')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='species_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='map_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_route', models.CharField(max_length=100)),
                ('tree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_app.trees')),
            ],
        ),
        migrations.CreateModel(
            name='download_occurrences_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_id', models.CharField(max_length=23, unique=True)),
                ('download_date', models.DateField(auto_now_add=True)),
                ('specie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_app.species')),
            ],
        ),
    ]
