# Generated by Django 3.0.3 on 2021-05-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download_occurrences_date',
            old_name='specie_id',
            new_name='specie',
        ),
        migrations.RenameField(
            model_name='map_images',
            old_name='tree_id',
            new_name='tree',
        ),
        migrations.RenameField(
            model_name='markers',
            old_name='specie_id',
            new_name='specie',
        ),
        migrations.RenameField(
            model_name='markers',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='specie_sequences',
            old_name='specie_id',
            new_name='specie',
        ),
        migrations.RenameField(
            model_name='trees',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='used_species',
            old_name='specie_id',
            new_name='specie',
        ),
        migrations.RenameField(
            model_name='used_species',
            old_name='tree_id',
            new_name='tree',
        ),
    ]
