# Generated by Django 3.0.3 on 2021-05-07 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0002_auto_20210506_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='species_app.users'),
        ),
        migrations.AlterField(
            model_name='markers',
            name='dataset_key',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='markers',
            name='identification_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='image_specie',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
