# Generated by Django 3.0.3 on 2021-05-10 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0003_auto_20210507_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequences',
            name='specie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='species_app.species'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='specie_sequences',
        ),
    ]
