# Generated by Django 3.0.3 on 2021-05-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0004_auto_20210510_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='used_species',
            name='specie',
        ),
        migrations.RemoveField(
            model_name='used_species',
            name='tree',
        ),
        migrations.AddField(
            model_name='trees',
            name='image_route',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='map_images',
        ),
        migrations.DeleteModel(
            name='used_species',
        ),
    ]
