# Generated by Django 3.2 on 2021-05-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0008_alter_sequences_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequences',
            name='sequence',
            field=models.CharField(max_length=16383),
        ),
    ]
