# Generated by Django 3.0.3 on 2021-05-13 18:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='trees',
            fields=[
                ('tree_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
                ('tree_route', models.CharField(max_length=100)),
                ('image_route', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='species',
            fields=[
                ('specie_id', models.AutoField(primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=100)),
                ('colloquial_name', models.CharField(max_length=20)),
                ('taxon_id', models.CharField(max_length=25)),
                ('image_specie', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='species_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='sequences',
            fields=[
                ('acc_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gene', models.CharField(max_length=20)),
                ('sequence', models.CharField(max_length=10000)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_app.species')),
            ],
        ),
        migrations.CreateModel(
            name='markers',
            fields=[
                ('marker_id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('identification_id', models.BigIntegerField(null=True)),
                ('dataset_key', models.CharField(max_length=150, null=True)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_app.species')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='species_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='download_occurrences_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_id', models.CharField(max_length=23, unique=True)),
                ('download_date', models.DateField(auto_now_add=True)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_app.species')),
            ],
        ),
    ]
