# Generated by Django 3.2 on 2021-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0002_blast_markers_with_names_ortholog_users_with_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='blast',
            name='specie_authors',
            field=models.CharField(default=False, max_length=1000),
        ),
    ]
