# Generated by Django 3.2 on 2021-05-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0003_blast_specie_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='image_specie',
        ),
        migrations.AlterField(
            model_name='blast',
            name='specie_authors',
            field=models.CharField(default=False, max_length=7000),
        ),
    ]
