# Generated by Django 3.2 on 2021-05-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0004_auto_20210523_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='blast_species_gen',
            fields=[
                ('acc_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=100)),
                ('gene', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'get_blast_species_gen',
                'managed': False,
            },
        ),
    ]
