# Generated by Django 3.2 on 2021-05-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0005_blast_species_gen'),
    ]

    operations = [
        migrations.CreateModel(
            name='blast_authors',
            fields=[
                ('acc_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=100)),
                ('gene', models.CharField(max_length=20)),
                ('specie_authors', models.CharField(default=False, max_length=7000)),
            ],
            options={
                'db_table': 'get_blast_authors',
                'managed': False,
            },
        ),
    ]
