# Generated by Django 3.2 on 2021-05-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0006_blast_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blast',
            name='gene',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
