# Generated by Django 3.2 on 2021-05-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0007_alter_blast_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='colloquial_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
