# Generated by Django 3.1.2 on 2021-05-27 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0009_alter_sequences_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='sequences_and_scientific_names',
            fields=[
                ('taxon_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=100)),
                ('sequence', models.TextField(max_length=50000)),
            ],
            options={
                'db_table': 'sequences_and_scientific_names',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='markers',
            old_name='specie',
            new_name='specie_id',
        ),
        migrations.RenameField(
            model_name='markers',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='markers',
            name='specie_id',
            field=models.ForeignKey(db_column='specie_id', on_delete=django.db.models.deletion.CASCADE, to='species_app.species'),
        ),
        migrations.AlterField(
            model_name='markers',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='species_app.users'),
        ),
    ]
